CREATE DATABASE customer_shopping_behavior;
USE customer_shopping_behavior;
show tables;
select * from customers limit 20;

# Q Total revenue generated by gender?
SELECT gender, SUM(`purchase_amount_(usd)`) AS total_revenue 
FROM customers 
GROUP BY gender;


# Q Customers used discount but still spent more than the average purchase amount?
SELECT customer_id , `purchase_amount_(usd)`
FROM customers
WHERE discount_applied = 'Yes' AND `purchase_amount_(usd)` > (SELECT AVG(`purchase_amount_(usd)`) FROM customers);


# Q Top 5 Products with the highest avg review rating?
SELECT item_purchased , ROUND(AVG(review_rating),2) AS average_rating
FROM customers
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;


# Q Average purchase amount between Standard & Express Shipping comparision?
SELECT shipping_type, AVG(`purchase_amount_(usd)`) AS average_purchase_amount
FROM customers
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type;


# Q Do subscribed customers spend more? Average spend and total spend between subscribers and non-subscribers comparision
SELECT subscription_status, COUNT(customer_id) AS total_customers,
ROUND(AVG(`purchase_amount_(usd)`),2) AS average_spent, ROUND(SUM(`purchase_amount_(usd)`),2) AS total_revenue
FROM customers
GROUP BY subscription_status;


# Q Top 5 products with highest percentage of purchase with discount applied?
WITH prod_count_cte AS
(SELECT item_purchased, COUNT(item_purchased) as products_count
FROM customers
WHERE discount_applied = 'YES'
GROUP BY item_purchased),
total_prod_cte AS(
SELECT *, SUM(products_count) OVER() AS total_products 
FROM prod_count_cte)
SELECT item_purchased, CONCAT(ROUND((Products_count/Total_products)*100,2),'%') AS purchase_percentage
FROM total_prod_cte
ORDER BY purchase_percentage DESC
LIMIT 5;


# Q Segment customers into New, Returning & Loyal based on their total number of previous purchases 
     -- and count of each segment
WITH CTE AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New Customers'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning Customers'
    ELSE 'Loyal Customers'
END AS 'customers_segmentation'
FROM customers
GROUP BY customer_id, previous_purchases)
SELECT customers_segmentation, COUNT(customers_segmentation) AS total_count
FROM CTE
GROUP BY customers_segmentation;


# Q Top 3 purchased products in each category?
WITH CTE AS
(
SELECT category,item_purchased, COUNT(item_purchased) as products_count,
DENSE_RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS product_rank
FROM customers 
GROUP BY category,item_purchased
)
SELECT product_rank, category, item_purchased, products_count 
FROM CTE 
WHERE product_rank <= 3;


# Q Are customers who are repeat (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,  COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases >= 5
GROUP BY subscription_status;


# Q Revenue contribution of each age group? 
SELECT age_group,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;